/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      container: {
        screens: {
          sm: '400px',
          md: '450px',
          lg: '728px',
          xl: '984px',
          '2xl': '1240px',
        },
      },
      colors: {
        'neutral-white' : '#FFFFFF',
        'neutral-100':'#F8F9FA',
        'neutral-200':'#E9ECEF',
        'neutral-300': '#DEE2E6',
        'neutral-400': '#CED4DA',
        'neutral-500': '#ADB5BD',
        'neutral-600': '#6C757D',
        'neutral-700': '#495057',
        'neutral-800': '#343A40',
        'neutral-900' : '#212529',
        'neutral-black': '#00000',
        'blue-selected': '#CBE4FE',
        'blue-hover': '#3F87FD',
        'blue-normal': '#0057FC',
        'blue-click': '#0043D8',
        'success-selected': '#EAFBD4',
        'success-hover': '#87D557',
        'success-normal': '#56BA28',
        'success-click': '#3D9F1D',
        'info-selected': '#CBFEF6',
        'info-hover': '#3EEEFA',
        'info-normal': '#00D4F8',
        'info-click': '#00A5D5',
        'warning-selected': '#FFF0D1',
        'warning-hover': '#FFAE53',
        'warning-normal': '#FF881A',
        'warning-click': '#DB6813',
        'danger-selected': '#FFE0D2',
        'danger-hover': '#FF6157',
        'danger-normal': '#FF1F25',
        'danger-click': '#DB162D',

        'heading': '#212529',
        'heading-inverted': '#F8F9FA',
        'normal': '#343A40',
        'normal-inverted': '#E9ECEF',
        'secondary': '#6C757D',
        'secondary-inverted': '#CED4DA',
        'button': '#FFFFFF',
        'button-inverted': '#212529',
        'disabled': '#ADB5BD',
      },
    },
  },
  plugins: [],
}